name: Deploy Bot

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      domain:
        description: 'Primary domain for your website'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add host key
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Copy deployment scripts to server
        run: |
          scp scripts/deploy-bot.sh scripts/setup-caddy.sh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~
      
      - name: Deploy the bot
        env:
          MATRIX_HOMESERVER_URL: ${{ secrets.MATRIX_HOMESERVER_URL }}
          MATRIX_USER_ID: ${{ secrets.MATRIX_USER_ID }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          MATRIX_ROOM_IDS: ${{ secrets.MATRIX_ROOM_IDS }}
          COMMAND_PREFIX: ${{ secrets.COMMAND_PREFIX }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          WEBSITE_DOMAIN: ${{ github.event.inputs.domain || secrets.WEBSITE_DOMAIN || 'example.com' }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            export MATRIX_HOMESERVER_URL=\"${MATRIX_HOMESERVER_URL}\"
            export MATRIX_USER_ID=\"${MATRIX_USER_ID}\"
            export MATRIX_ACCESS_TOKEN=\"${MATRIX_ACCESS_TOKEN}\"
            export MATRIX_ROOM_IDS=\"${MATRIX_ROOM_IDS}\"
            export COMMAND_PREFIX=\"${COMMAND_PREFIX}\"
            export OPENAI_API_KEY=\"${OPENAI_API_KEY}\"
            export ANTHROPIC_API_KEY=\"${ANTHROPIC_API_KEY}\"
            export WEBSITE_DOMAIN=\"${WEBSITE_DOMAIN}\"
            export GITHUB_REPOSITORY=\"${GITHUB_REPOSITORY}\"
            
            # Make the scripts executable
            chmod +x ~/deploy-bot.sh
            
            # Run the deployment script
            ~/deploy-bot.sh
          "
          
      - name: Set up Caddy
        env:
          WEBSITE_DOMAIN: ${{ github.event.inputs.domain || secrets.WEBSITE_DOMAIN || 'example.com' }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            # Make the script executable
            chmod +x ~/setup-caddy.sh
            
            # Run the Caddy setup script
            ~/setup-caddy.sh \"${WEBSITE_DOMAIN}\"
          "
          
      - name: Clean up scripts
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            rm ~/deploy-bot.sh ~/setup-caddy.sh
          "
      
      - name: Output success message
        run: |
          echo "✅ Deployment complete!"
          echo "🤖 Bot is now running on the server"
          echo "🌐 Website is available at:"
          echo "   - Production: https://${{ github.event.inputs.domain || secrets.WEBSITE_DOMAIN || 'example.com' }}"
          echo "   - Preview: https://preview.${{ github.event.inputs.domain || secrets.WEBSITE_DOMAIN || 'example.com' }}"